# Timeout for a corpse to despawn
# Set to -1 to disable (strongly despised as corpses load chunks)
corpseRemovalTimeout: 3600 # Ticks

# Entity used for corpse hitbox
hitboxEntity: turtle

# The name of the corpses inventory
guiName: "{}&r's corpse"

# Store dropped exp in corpse (give to first opener)
expSupport: true

# Delete corpse if the inventory is empty
removeIfEmpty: false

# Don't spawn the corpse if it'll end up in fire or lava
dontSpawnIn:
  fire: false
  lava: true
