name: An0mCorpses
version: '${project.version}'
main: dev.an0m.an0mcorpses.An0mCorpses
api-version: '1.16'
load: STARTUP
website: an0m.dev
author: An0m
description: A simple lootable corpses plugin

commands:
  corpse:
    permission: corpse.admin

permissions:
  corpse.admin:
    default: op
